### PR TITLE
Add support for followupEvent in response

### PR DESCRIPTION
**Pull request by wiki-wolters**

### CODE REVIEW

**Comment by ndjido** [comment]
Hello @lance-wolters, your PR enabling the `followupEvent` to be sent from the webhook looks nice.  Could you please sign the CLA as @googlebot suggested so your PR can be reviewed and merged.  Thanks in advance.

**Comment by lance-wolters** [comment]
I signed it!

**Comment by ndjido** [comment]
@lance-wolters I think your signature is not taken into account. I guess it may have to do with you Git global-config. You’ll need to fix it and amend your commit because @googlebot is still keeping the `no:cla` tag.

**Comment by lance-wolters** [comment]
I completed the CLA organization form, and specified my CTO as the
authorized signatory, but he never received an email with instructions on
how to sign. So now we are stuck.

**Comment by lance-wolters** [comment]
I signed it!

**Comment by lance-wolters** [comment]
I signed it!

**Comment by lance-wolters** [comment]
I signed it!

**Comment by Fleker** [comment]
It does not appear that either account, wiki-wolters or lance-wolters, has not completely signed the CLA. If you have, maybe you should try to redo the PR with the git account that you signed with.

**Comment by lance-wolters** [comment]
I signed it!

**Comment by lance-wolters** [comment]
I received a forwarded email this morning from Google stating that "All parties have completed Google Contributor License Agreement"

**Comment by lance-wolters** [comment]
I've now also signed a CLA for my personal account, from which this branch first originated.

**Comment by Fleker** [comment]
@wiki-wolters has signed the CLA, but @lance-wolters has not and commits from that account right now cannot be accepted. Can you make another PR with the commit coming from your personal account?

**Comment by Canain** [comment]
Closing this so we can retry this with another CL.

**Pull request closed without merging**
