### PR TITLE
fix askForSignIn in ApiAiApp

### PR DESCRIPTION
**Pull request by patjackson52**
- fulfillSignIn was missing type in data
 - passing test

### CODE REVIEW

**Comment by patjackson52** [comment]
I signed it

**Comment by patjackson52** [comment]
Didn't forget, just less familiar with the actions-sdk.  I've updated with corresponding actions-sdk-app data

**Comment by patjackson52** [comment]
CLA resubmitted

**Comment by patjackson52** [comment]
any update on this?

**Comment by smishra2** [comment]
I'm not sure these changes are necessary. Are you finding that the API is not working for you when this change isn't in place?

**Comment by patjackson52** [comment]
Yes, without the changes I do not get a response from Google at all, and
the action exits.

**Comment by patjackson52** [comment]
Any update on this?

**Comment by smishra2** [comment]
Sorry, I'm not able to reproduce your issue. Could you confirm that the current version of the client lib does not work for you even when you check the Transactions checkbox in the Actions Console? And could you also paste here your JSON response for the SIGN_IN intent without your change?

**Comment by patjackson52** [comment]
I am still getting no response from after app.askForSignIn().  Below is the response sent back from the webhook.  Not sure how transactions are related to signin, but I have now tested with the transaction check box enable as well with the same results.

`{
"speech":"PLACEHOLDER_FOR_SIGN_IN",
"contextOut":[
{
"name":"_actions_on_google_",
"lifespan":100,
"parameters":{
}
}
],
"data":{
"google":{
"expectUserResponse":true,
"isSsml":false,
"noInputPrompts":[
],
"systemIntent":{
"intent":"actions.intent.SIGN_IN",
"data":{
}
}
}
}
}`

**Comment by smishra2** [comment]
The SIGN_IN intent currently requires Transactions APIs to be enabled, as it's meant to be used as part of a checkout flow. Only sign in at invocation time is available w/o transactions APIs. 

Are you using API.AI? Is your sign in page live and available? Are you using another intent in your API.AI agent which receives the "actions_intent_SIGN_IN" event?

**Comment by patjackson52** [comment]
Still getting no response from when doing askForSignIn().  Using 1.2.0 of client lib, transactions enabled.  This is the debug message I get in simulator.

Debug message

**Comment by smishra2** [comment]
Ah, yes the app requires the Oauth information (credentials, token endpoints, etc) to be entered in the Account Linking section of the [Actions Console](console.actions.google.com) project. This is true whether the sign in is required at invocation time or mid-dialog (i.e. with this SIGN_IN intent). 

When this information is not entered, what is the observed behavior with your change? It shouldn't work with your change either, I believe.

**Pull request closed without merging**
