### PR TITLE
Fix typo in docs for `askWithList`

### PR DESCRIPTION
**Pull request by kvas-damian**
Fix for https://github.com/actions-on-google/actions-on-google-nodejs/issues/75

Fix typo in `askWithList` docs

### CODE REVIEW

**Comment by Fleker** [comment]
Hey, thanks for doing this PR. Do you know of any tools that can check the syntax of JSDoc examples? It'd be great to incorporate such a tool into pre-submit tasks.

**Comment by joelhegg** [comment]
Also see #63. @Fleker These were discovered when running this package through tsd-jsdoc. Some people use it to validate their jsdoc.

**Comment by kvas-damian** [comment]
I never used such tool. Maybe we could try another approach: move code samples into separate directory? Then we could use regular linting tools to catch such issues.

**Comment by Canain** [comment]
Looks good. Let us know if you find more problems like this. We will investigate a more automated way of finding stuff like this.

**Pull request merged**
